### ISSUE TITLE
Blank page after update

### ISSUE THREAD

**Issue by zebrahosting** [YetiForceCompany/UpdatePackages#16]
Tried an update with the 1.3->1.4 v2 update and got  blank page.
where do I find the SQL update file to test this manually?
(Already copied the files over)

**Comment by bpabiszczak** [comment]
Specially for you I wrote an article explaining how to report bugs.  :/ When its translation is complete, you will see a new Tweet about it.

A blank screen might appear because you didn’t change PHP version before the update [after updating it is required to change it again if you set in in htaacess, because we overwrite it]. It is impossible to separate queries to the data base, because there are e.g. xml files that install functionalities and create tables. It is necessary to restore a copy before the update and then update again. If you don’t have a copy [that’s not good], then you need to change a version number in config/version.php and install the update again [it will again perform changes in the data base].

If the problem isn’t related to PHP, then it’s time to learn how to debug the application [the instruction is here: https://yetiforce.com/en/ideas,-changes,-bugs/bugs/115-debugging.html ]
